### General settings.
## The name of singer
spk: "kuroppoid"
## exp tag(for managing experiments)
tag: "jp_qst_crazy_mono_005_173D"

## Directory of NNSVS
nnsvs_root: "$HOME/nnsvs"

### Pyinsy related settings.
## Sinsy dictionary directory
# ONIKU_KURUMI_UTAGOE_DB contains the unvoiced vowels "I" and "U".
# To enable the unvoiced vowels, modified version of sinsy dictionary files
# are needed.
sinsy_dic: "./dic"

## HTS-style question used for extracting musical/linguistic context from musicxml files
question_path: "./hed/jp_qst_crazy_mono_005_173D.hed"

# File I/O directories
in_lab_dir: "./01_lab"
utt_list: "./02_uttlist/utt_list.txt"
out_wav_dir: "./03_wav"

## sample_rate
sample_rate: "96000"

###########################################################
#                SYNTHESIS SETTING                        #
###########################################################
timelag_synthesis: "defaults"
duration_synthesis: "defaults"
acoustic_synthesis: "defaults"

# latest.pth or best.pth
timelag_eval_checkpoint: "best_loss.pth"
duration_eval_checkpoint: "best_loss.pth"
acoustic_eval_checkpoint: "latest.pth"
